name: Deploy via SFTP
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync files (SFTP/SSH via rsync)
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.FTP_SERVER }}
          remote-user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          desination-path: ${{ secrets.DESTINATION_PATH }}
          source-path: ./dist/                # your build output
          rsync-options: --archive --verbose --compress --delete-after --human-readable
          server-dir: /public_html/app/    # your webroot or subfolder
          dangerous-clean-slate: true      # wipes server-dir before upload
