name: Sync files (SFTP/SSH via rsync)
  uses: SamKirkland/web-deploy@v1
  with:
    target-server: your.server.com
    remote-user: ${{ secrets.SSH_USER }}
    private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    destination-path: /home/ACCOUNT/public_html/_deploy_test/
    source-path: ./dist/
    rsync-options: --archive --verbose --compress --delete-after --human-readable
    dangerous-clean-slate: true
