# .github/workflows/deploy-sftp.yml
name: Deploy via SFTP/FTPS
on:
  push:
    branches: [ main ]
    paths:
      - '**/*'
      - '!.github/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 - name: Sync files (SFTP/SSH via rsync)
  uses: SamKirkland/web-deploy@v1
  with:
    target-server: your.server.com
    remote-user: ${{ secrets.SSH_USER }}
    private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    destination-path: /home/ACCOUNT/public_html/_deploy_test/
    source-path: ./dist/
    rsync-options: --archive --verbose --compress --delete-after --human-readable
    dangerous-clean-slate: true
