# .github/workflows/deploy-sftp.yml
name: Deploy via SFTP/FTPS
on:
  push:
    branches: [ main ]
    paths:
      - '**/*'
      - '!.github/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to host
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: ${{ secrets.FTP_PORT || 22 }}
          local-dir: ./mileage.yetirc.com/
          server-dir: /home/sawi0011/mileage.yetirc.com/web
          exclude: |
            **/.git*
            .github/**
            **/node_modules/**
            **/.DS_Store
          dangerous-clean-slate: true
