name: Deploy to DreamHost (SFTP)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via SFTP (password)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.FTP_SERVER }}     # e.g. sftp.dreamhost.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local-path: ./
          remote_path: /home/sawi0011/mileage.yetirc.com/
          sftp_only: true
          exclude: |
            **/.git*
            .github/**
            **/.DS_Store
            **/node_modules/**
          dangerous-clean-slate: true
