name: Deploy via SFTP
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync files (SFTP/SSH via rsync)
        uses: SamKirkland/web-deploy@v1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          local-dir: dist/                 # your build output
          server-dir: /public_html/app/    # your webroot or subfolder
          dangerous-clean-slate: true      # wipes server-dir before upload
