name: Deploy to DreamHost (SFTP)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.5

      - name: Upload via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}     # e.g. sftp.dreamhost.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          local-dir: ./
          server-dir: /home/sawi0011/mileage.yetirc.com/
          exclude: |
            **/.git*
            .github/**
            **/.DS_Store
            **/node_modules/**
          dangerous-clean-slate: true
