name: Release & PWA Version Bump

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Semver bump: patch | minor | major'
        required: true
        default: 'patch'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine release type
        id: releasetype
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "type=${{ github.event.inputs.release_type }}" >> "$GITHUB_OUTPUT"
          else
            echo "type=patch" >> "$GITHUB_OUTPUT"
          fi

      - name: Get latest tag (or bootstrap)
        id: latest
        run: |
          set -e
          if git describe --tags --abbrev=0 >/dev/null 2>&1; then
            LATEST_TAG="$(git describe --tags --abbrev=0)"
          else
            # If no tag exists yet, treat current as v1.0.0 (pre-bump state)
            LATEST_TAG="v1.0.0"
          fi
          echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"

      - name: Bump semver
        id: bump
        run: |
          old="${{ steps.latest.outputs.tag }}"
          old="${old#v}"   # strip leading v
          IFS='.' read -r MAJOR MINOR PATCH <<EOF
          $old
          EOF
          case "${{ steps.releasetype.outputs.type }}" in
            major) MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0 ;;
            minor) MINOR=$((MINOR+1)); PATCH=0 ;;
            patch|*) PATCH=$((PATCH+1)) ;;
          esac
          new="$MAJOR.$MINOR.$PATCH"
          echo "version=$new" >> "$GITHUB_OUTPUT"
          echo "vnew=v$new"   >> "$GITHUB_OUTPUT"

      - name: Update service worker cache name
        run: |
          VERSION="${{ steps.bump.outputs.version }}"
          if [ -f service-worker.js ]; then
            sed -i -E 's/(const[[:space:]]+CACHE_NAME[[:space:]]*=[[:space:]]*")[^"]+(")/\1fuel-runtime-calculator-v'"$VERSION"'\2/' service-worker.js
          fi

      - name: Update cache-busting query strings in index.html
        run: |
          VERSION="${{ steps.bump.outputs.version }}"
          if [ -f index.html ]; then
            sed -i -E 's|(style\.css\?v=)[^"]+|\1'"$VERSION"'|g' index.html
            sed -i -E 's|(script\.js\?v=)[^"]+|\1'"$VERSION"'|g' index.html
          fi

      - name: Commit version bump (if any changes)
        run: |
          VERSION="${{ steps.bump.outputs.version }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore: bump PWA version to v${VERSION}"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Create tag
        run: |
          VNEW="${{ steps.bump.outputs.vnew }}"
          git tag "$VNEW"
          git push origin "$VNEW"

      - name: Create release zip
        run: |
          VERSION="${{ steps.bump.outputs.version }}"
          ZIP="fuel-runtime-v${VERSION}.zip"
          zip -r "$ZIP" . -x "*.git*" ".github/workflows/*"
          echo "ZIP_NAME=$ZIP" >> "$GITHUB_ENV"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.vnew }}
          name: ${{ steps.bump.outputs.vnew }}
          generate_release_notes: true
          files: ${{ env.ZIP_NAME }}
